### ISSUE TITLE
Creating library with no package.json

### ISSUE THREAD

**Issue by wefarrell** [transitive-bullshit/create-react-library#141]
I installed this using `npm install -g transitive-bullshit/create-react-library` because when I installed with without specifying the repo it used a previous version with babel 6.

Now when I run `create-react-library` the installation fails with the following error:

```
✔ Copying default template to /Users/willfarrell/dev/opus-graphs-library
✖ Running yarn install and yarn link
{ Error: Command failed: /bin/sh -c yarn link
error Couldn't find a package.json file in "/Users/willfarrell/dev/opus-graphs-library"

yarn link v1.13.0
info Visit https://yarnpkg.com/en/docs/cli/link for documentation about this command.

    at makeError (/usr/local/lib/node_modules/create-react-library/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/usr/local/lib/node_modules/create-react-library/node_modules/execa/index.js:278:16)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
  code: 1,
  stdout:
   'yarn link v1.13.0\ninfo Visit https://yarnpkg.com/en/docs/cli/link for documentation about this command.\n',
  stderr:
   `error Couldn't find a package.json file in "/Users/willfarrell/dev/opus-graphs-library"\n`,
  failed: true,
  signal: null,
  cmd: '/bin/sh -c yarn link',
  timedOut: false,
  killed: false }
```

Opening up the directory shows only the following files:
```
README.md	node_modules	yarn.lock
```

**Comment by transitive-bullshit** [comment]
Hmmm, never seen this before. What version of `Node.js`, `yarn`, and which OS?

**Comment by RobMayer** [comment]
same exact issue, I'm afraid.

node v10.13.0
yarn v1.16.0
windows 7
