### ISSUE TITLE
jsdom causing issues when creating library

### ISSUE THREAD

**Issue by richardskinner** [transitive-bullshit/create-react-library#192]
Hi,

When i run create-react-library i get the following error

> /Users/richardskinner/Sites/react-library-packages/test-react-package/node_modules/jsdom/lib/jsdom/living/helpers/dates-and-times.js:235
  } catch {
          ^
> SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions..js (/Users/richardskinner/Sites/react-library-packages/test-react-package/node_modules/rollup/bin/rollup:1263:17)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)

I'm using node v8.10

Anyone have any ideas why this would happen?

**Comment by transitive-bullshit** [comment]
node 8 is pretty old at this point - whether that's the issue or not, you should definitely upgrade to at least 12.

**Comment by richardskinner** [comment]
Upgrading my node worked. Thanks
