### ISSUE TITLE
Path /usr/local/lib/node_modules/create-react-library/template/default/.editorconfig is not in cwd

### ISSUE THREAD

**Issue by BertieGo** [transitive-bullshit/create-react-library#212]
````
create-react-library
? Package Name rc-i18n
? Package Description Made with create-react-library
? Author's GitHub Handle
? GitHub Repo Path /rc-i18n
? License MIT
? Package Manager npm
? Template default
Error: Path /usr/local/lib/node_modules/create-react-library/template/default/.editorconfig is not in cwd /Users/huangwei/learn/npm
    at ensureAbsolutePathForCwd (/usr/local/lib/node_modules/create-react-library/node_modules/globby/gitignore.js:52:9)
    at p (/usr/local/lib/node_modules/create-react-library/node_modules/globby/gitignore.js:59:55)
    at arrayUnion.filter.path_ (/usr/local/lib/node_modules/create-react-library/node_modules/globby/index.js:135:47)
    at Array.filter (<anonymous>)
    at module.exports (/usr/local/lib/node_modules/create-react-library/node_modules/globby/index.js:135:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
````

node version: 
````
node -v
v10.16.0
````

**Comment by teehtheg** [comment]
I'm experiencing the exact same issue with slightly different library setup (i.e. npm & typescript)

**Comment by sidv93** [comment]
Experiencing the same error with node 12.16.1

**Comment by ninjaPixel** [comment]
I'm also getting this with node 12.15.0

**Comment by transitive-bullshit** [comment]
Sorry; this was a mistake on my part. Please try upgrading to v3.0.4 and let me know if this is fixed for you.

Please follow up in https://github.com/transitive-bullshit/create-react-library/issues/213 to keep the discussion focused.

Thanks!
