### ISSUE TITLE
yarn/npm install fails on new project

### ISSUE THREAD

**Issue by fitzmode** [transitive-bullshit/create-react-library#227]
Creating a new project fails at `yarn install` / `npm install`.

```
fitz:~ fitzmode$ node -v
v12.16.2
```
System is Mac OSX 10.14.5

```
fitz:~ fitzmode$ npx create-react-library userefs
npx: installed 151 in 102.87s
? Package Name userefs
? Package Description Made with create-react-library
? Author's GitHub Handle fitzmode
? GitHub Repo Path fitzmode/userefs
? License MIT
? Package Manager yarn
? Template typescript
⠋ Copying typescript template to /Users/fitzmode/userefs
.editorconfig
.eslintignore
.eslintrc
.prettier.json
.travis.yml
README.md
package.json
tsconfig.json
tsconfig.test.json
src/.eslintrc
src/index.test.tsx
src/index.tsx
src/styles.module.css
src/typings.d.ts
example/README.md
example/package.json
example/src/App.js
example/src/App.test.js
example/src/index.css
example/src/index.js
example/public/favicon.ico
example/public/index.html
example/public/manifest.json
✔ Copying typescript template to /Users/fitzmode/userefs

Initializing npm dependencies. This will take a minute.

✔ Running yarn install in root directory
✖ Running yarn install in example directory
Error: Command failed with exit code 1: yarn install
warning react-scripts > jest-environment-jsdom-fourteen > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning react-scripts > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
warning react-scripts > resolve-url-loader > rework > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning react-scripts > resolve-url-loader > rework > css > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
warning react-scripts > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
warning react-scripts > resolve-url-loader > rework > css > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
warning react-scripts > workbox-webpack-plugin > workbox-build > strip-comments > babel-plugin-transform-object-rest-spread > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
warning "react-scripts > sass-loader@8.0.2" has unmet peer dependency "node-sass@^4.0.0".
warning "react-scripts > sass-loader@8.0.2" has unmet peer dependency "sass@^1.3.0".
warning "react-scripts > sass-loader@8.0.2" has unmet peer dependency "fibers@>= 3.1.0".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
error An unexpected error occurred: "Reduce of empty array with no initial value".
yarn install v1.7.0
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
info If you think this is a bug, please open a bug report with the information provided in "/Users/fitzmode/userefs/example/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
    at makeError (/Users/fitzmode/.npm/_npx/53082/lib/node_modules/create-react-library/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/Users/fitzmode/.npm/_npx/53082/lib/node_modules/create-react-library/node_modules/execa/index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async pEachSeries (/Users/fitzmode/.npm/_npx/53082/lib/node_modules/create-react-library/node_modules/p-each-series/index.js:8:3) {
  shortMessage: 'Command failed with exit code 1: yarn install',
  command: 'yarn install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'yarn install v1.7.0\n' +
    'info No lockfile found.\n' +
    '[1/4] Resolving packages...\n' +
    '[2/4] Fetching packages...\n' +
    '[3/4] Linking dependencies...\n' +
    'info If you think this is a bug, please open a bug report with the information provided in "/Users/fitzmode/userefs/example/yarn-error.log".\n' +
    'info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.',
  stderr: 'warning react-scripts > jest-environment-jsdom-fourteen > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142\n' +
    'warning react-scripts > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142\n' +
    'warning react-scripts > resolve-url-loader > rework > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated\n' +
    'warning react-scripts > resolve-url-loader > rework > css > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated\n' +
    'warning react-scripts > jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()\n' +
    'warning react-scripts > resolve-url-loader > rework > css > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated\n' +
    'warning react-scripts > workbox-webpack-plugin > workbox-build > strip-comments > babel-plugin-transform-object-rest-spread > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.\n' +
    'warning "react-scripts > sass-loader@8.0.2" has unmet peer dependency "node-sass@^4.0.0".\n' +
    'warning "react-scripts > sass-loader@8.0.2" has unmet peer dependency "sass@^1.3.0".\n' +
    'warning "react-scripts > sass-loader@8.0.2" has unmet peer dependency "fibers@>= 3.1.0".\n' +
    'warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".\n' +
    'error An unexpected error occurred: "Reduce of empty array with no initial value".',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by Avalanche2307** [comment]
I am facing the exact same issue. The installation fails due to use of deprecated libraries (request and core-js).

**Comment by lynx1120** [comment]
me tooooo, same issue

**Comment by neilh-cogapp** [comment]
I had the same issue. Worked around it with the following:
```
rm yarn.lock
yarn
```

Node v12.14.1
