### ISSUE TITLE
TypeError: Command failed: npm install timedPromise.finally is not a function

### ISSUE THREAD

**Issue by abhion** [transitive-bullshit/create-react-library#252]
I followed the instructions and  I get this after I run `npx create-react-library`:

`√ Copying default template to D:\DCT\tasks\react-analog-clock

Initializing npm dependencies. This will take a minute.

- Running npm install in root directory
× Running npm install in root directory
{ TypeError: Command failed: npm install
timedPromise.finally is not a function
    at setExitHandler (C:\Users\abhi_\AppData\Roaming\npm\node_modules\create-react-library\node_modules\execa\lib\kill.js:102:29)
    at execa (C:\Users\abhi_\AppData\Roaming\npm\node_modules\create-react-library\node_modules\execa\index.js:100:22)
    at pEachSeries (C:\Users\abhi_\AppData\Roaming\npm\node_modules\create-react-library\lib\create-library.js:118:12)
    at pEachSeries (C:\Users\abhi_\AppData\Roaming\npm\node_modules\create-react-library\node_modules\p-each-series\index.js:8:9)
    at <anonymous>
  originalMessage: 'timedPromise.finally is not a function',
  shortMessage: 'Command failed: npm install\ntimedPromise.finally is not a function',
  command: 'npm install',
  exitCode: undefined,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }
`

**Comment by psyycker** [comment]
Did you have this error straight after executing `npx create-react-library` ?
Could you provide your version of nodejs (`node -v`) and the version of npm as well? (`npm -v`)
