### ISSUE TITLE
Bundle Material-UI in library

### ISSUE THREAD

**Issue by semopz** [transitive-bullshit/create-react-library#278]
I'm trying to bundle React and MUI into a library. I can't use peer dependencies because the package where this library will be used is forced to use a very old version of React. Is this scenario supported with `create-react-library`?

If I just bundle React, it works well 👍. Things go wrong when I include MUI (Fluent UI doesn't work either) 👎 as part of devDependencies. Error below and can be recreated by cloning [this](https://github.com/semopz/bundle-all) and running `npm i` and `npm run-script build`

```markdown
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@6.9.0
3 info using node@v10.16.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle bundle-all@1.0.0~prebuild: bundle-all@1.0.0
6 info lifecycle bundle-all@1.0.0~build: bundle-all@1.0.0
7 verbose lifecycle bundle-all@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle bundle-all@1.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Dev\github\bundle-all\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Dev\github\bundle-all\node_modules\.bin;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\RogueKiller;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\moi\AppData\Local\Programs\Fiddler;C:\Users\moi\AppData\Roaming\npm
9 verbose lifecycle bundle-all@1.0.0~build: CWD: C:\Dev\github\bundle-all
10 silly lifecycle bundle-all@1.0.0~build: Args: [ '/d /s /c',
10 silly lifecycle   'microbundle-crl --no-compress --format modern,cjs' ]
11 silly lifecycle bundle-all@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle bundle-all@1.0.0~build: Failed to exec build script
13 verbose stack Error: bundle-all@1.0.0 build: `microbundle-crl --no-compress --format modern,cjs`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid bundle-all@1.0.0
15 verbose cwd C:\Dev\github\bundle-all
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.16.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error bundle-all@1.0.0 build: `microbundle-crl --no-compress --format modern,cjs`
22 error Exit status 1
23 error Failed at the bundle-all@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

Any suggestions welcome!

**Comment by picninim** [comment]
Any update?
