### ISSUE TITLE
'npm i' not working in 'example' folder

### ISSUE THREAD

**Issue by futurfutur** [transitive-bullshit/create-react-library#332]
updated npm from 6 to 7.6.1 version
now while trying to 'npm i' in  'example' folder getting following error:

npm ERR! code 1
npm ERR! path /Users/<...>/node_modules/typescript
npm ERR! command failed
npm ERR! command sh -c gulp build-eslint-rules
npm ERR! [16:30:28] Local modules not found in ~/<...>/typescript
npm ERR! [16:30:28] Try running: npm install

any way to fix this?

**Comment by jpaholik** [comment]
I'm having the same problem
```
Running npm install in example directory
Error: Command failed with exit code 1: npm install
npm ERR! code 1
npm ERR! path C:\Users\<...>\node_modules\typescript
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c gulp build-eslint-rules
npm ERR! [09:17:17] Local modules not found in ~\<...>\node_modules\typescript
npm ERR! [09:17:17] Try running: npm install

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<...>
    at makeError (C:\Users\<...>\node_modules\create-react-library\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\<...>\node_modules\create-react-library\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async pEachSeries (C:\Users\<...>\node_modules\create-react-library\node_modules\p-each-series\index.js:8:3) {
```

Any help would be appreciated

**Comment by sgmonda** [comment]
I'm experiencing the same issue since I upgraded `npm` this morning. Downgrading it to a previous version solved the problem for me. At least it is a temporary fix:

```
$ npm install -g npm@6.14.13
```

Then:

```
$ npm i
``` 

If this doesn't work as is, try to remove `node_modules` and `package-lock.json` after downgroading and before `npm i`. 

Hope this helps.

**Comment by edwinork** [comment]
This seems related to #293 

I was able to resolve it by applying the following [suggestion](https://github.com/transitive-bullshit/create-react-library/issues/293#issuecomment-779580256).
