### ISSUE TITLE
create-react-library failed on example

### ISSUE THREAD

**Issue by bostandyksoft** [transitive-bullshit/create-react-library#349]
I've tried to run create-react-library on Windows 10, but it fails

```
PS E:\javascript\controls> npx create-react-library ois-controls
? Package Name ois-controls
? Package Description Made with create-react-library
? Author's GitHub Handle avmakarov
? GitHub Repo Path avmakarov/ois-controls
? License MIT
? Package Manager npm
? Template typescript
- Copying typescript template to E:\javascript\controls\ois-controls
.editorconfig
.eslintignore
.eslintrc
.prettierrc
.travis.yml
package.json
README.md
tsconfig.json
tsconfig.test.json
example/package.json
example/README.md
example/tsconfig.json
src/.eslintrc
src/index.test.tsx
src/index.tsx
src/styles.module.css
src/typings.d.ts
example/src/App.test.tsx
example/src/App.tsx
example/src/index.css
example/src/index.tsx
example/src/react-app-env.d.ts
example/src/setupTests.ts
example/public/favicon.ico
example/public/index.html
example/public/manifest.json
√ Copying typescript template to E:\javascript\controls\ois-controls

Initializing npm dependencies. This will take a minute.

√ Running npm install in root directory
× Running npm install in example directory
Error: Command failed with exit code 1: npm install
npm ERR! code 1
npm ERR! path E:\javascript\controls\ois-controls\node_modules\typescript
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c gulp build-eslint-rules
npm ERR! [09:09:45] Local modules not found in E:\javascript\controls\ois-controls\node_modules\typescript
npm ERR! [09:09:45] Try running: npm install

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\avmakarov\AppData\Local\npm-cache\_logs\2021-06-14T02_09_45_685Z-debug.log
    at makeError (C:\Users\avmakarov\AppData\Roaming\npm\node_modules\create-react-library\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\avmakarov\AppData\Roaming\npm\node_modules\create-react-library\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async pEachSeries (C:\Users\avmakarov\AppData\Roaming\npm\node_modules\create-react-library\node_modules\p-each-series\index.js:8:23) {
  shortMessage: 'Command failed with exit code 1: npm install',
  command: 'npm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'npm ERR! code 1\n' +
    'npm ERR! path E:\\javascript\\controls\\ois-controls\\node_modules\\typescript\n' +
    'npm ERR! command failed\n' +
    'npm ERR! command C:\\WINDOWS\\system32\\cmd.exe /d /s /c gulp build-eslint-rules\n' +
    'npm ERR! [\u001b[90m09:09:45\u001b[39m] Local modules not found in E:\\javascript\\controls\\ois-controls\\node_modules\\typescript\n' +
    'npm ERR! [\u001b[90m09:09:45\u001b[39m] Try running: npm install\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     C:\\Users\\avmakarov\\AppData\\Local\\npm-cache\\_logs\\2021-06-14T02_09_45_685Z-debug.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

```
PS E:\javascript\controls> node --version
v12.13.1
PS E:\javascript\controls> npm --version
7.6.0
```

I cant understand what should i do to fix it.

Best regards.

**Comment by rehansattar** [comment]
Try running `npm install` in the example directory manually. Or another option could be to use `yarn`.  See if that works 😄

**Comment by vaibhavshn** [comment]
This helped: https://github.com/transitive-bullshit/create-react-library/issues/293#issuecomment-779580256
