### ISSUE TITLE
Creating new npm typescript library causes error: No gulpfile found

### ISSUE THREAD

**Issue by RichardPriddy** [transitive-bullshit/create-react-library#369]
When creating a new library with the create-react-library command, npm install works successfully on the root project, however when running npm install on the example folder, an exception is thrown:

```
 ❯  create-react-library 
? Package Name test
? Package Description Made with create-react-library
? Author's GitHub Handle RichardPriddy
? GitHub Repo Path RichardPriddy/test
? License ISC
? Package Manager npm
? Template typescript
- Copying typescript template to C:\Projects\temp\test
.editorconfig
.eslintignore
.eslintrc
.prettierrc
.travis.yml
package.json
README.md
tsconfig.json
tsconfig.test.json
example/package.json
example/README.md
example/tsconfig.json
src/.eslintrc
src/index.test.tsx
src/index.tsx
src/styles.module.css
src/typings.d.ts
example/src/App.test.tsx
example/src/App.tsx
example/src/index.css
example/src/index.tsx
example/src/react-app-env.d.ts
example/src/setupTests.ts
example/public/favicon.ico
example/public/index.html
example/public/manifest.json
√ Copying typescript template to C:\Projects\temp\test

Initializing npm dependencies. This will take a minute.

√ Running npm install in root directory
× Running npm install in example directory
Error: Command failed with exit code 1: npm install
npm ERR! code 1
npm ERR! path C:\Projects\temp\test\node_modules\typescript
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c gulp build-eslint-rules
npm ERR! [11:09:47] No gulpfile found

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\rpriddy\AppData\Local\npm-cache\_logs\2022-06-01T10_09_45_881Z-debug-0.log
    at makeError (C:\Users\rpriddy\AppData\Roaming\npm\node_modules\create-react-library\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\rpriddy\AppData\Roaming\npm\node_modules\create-react-library\node_modules\execa\index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async pEachSeries (C:\Users\rpriddy\AppData\Roaming\npm\node_modules\create-react-library\node_modules\p-each-series\index.js:8:23) {
  shortMessage: 'Command failed with exit code 1: npm install',
  command: 'npm install',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'npm ERR! code 1\n' +
    'npm ERR! path C:\\Projects\\temp\\test\\node_modules\\typescript\n' +
    'npm ERR! command failed\n' +
    'npm ERR! command C:\\WINDOWS\\system32\\cmd.exe /d /s /c gulp build-eslint-rules\n' +
    'npm ERR! [\x1B[90m11:09:47\x1B[39m] No gulpfile found\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     C:\\Users\\rpriddy\\AppData\\Local\\npm-cache\\_logs\\2022-06-01T10_09_45_881Z-debug-0.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by transitive-bullshit** [comment]
This tool is no longer actively maintained. I suggest using either [tsup](https://github.com/egoist/tsup), [tsdx](https://github.com/jaredpalmer/tsdx), or [microbundle](https://github.com/developit/microbundle).

Here's an [article](https://transitivebullsh.it/javascript-dev-tools-in-2022#823feddaa1bb4edea19042852b0a5b54) I wrote in April 2022 which should help you decide between these different tools.
