### ISSUE TITLE
Issue using create-react-library on node 9.2.11 (nvm)

### ISSUE THREAD

**Issue by keul** [transitive-bullshit/create-react-library#48]
I'm on a MacOS machine High Sierra.
I've installed a _new_ nvm env with node 9.11.2, then just installed globally create-react-library and yarn.

However I'm not able to run the executable:

```
$ create-react-library
internal/modules/cjs/loader.js:550
    throw err;
    ^

Error: Cannot find module 'isexe'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/Users/keul/.nvm/versions/node/v9.11.2/lib/node_modules/create-react-library/node_modules/which/which.js:10:13)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
```

**Comment by keul** [comment]
Installing a new v8 node env (8.11.3) I had no issue.

**Comment by transitive-bullshit** [comment]
Interesting -- thanks for the report @keul.

How are you creating the new env, specifically? When I do `nvm install 9.11.2`, it installs the correct version of node but my global npm and yarn still exist, as do all previous globally installed binaries.

Are you sure you're using the version of `create-react-library` that was installed globally with the correct version of `node`? That's the only real explanation I can see for what's going on here, as I'm unable to reproduce this issue locally.

**Comment by keul** [comment]
Uhm... sorry. I tested the procedure from stratch and now it worked 😕 
Probably I did something stupid this morning.

Only a side (trivial) issue:

```
$ cd /tmp/
$ create-react-library
? Package Name test
? Package Description Testing issue 48
? Author's GitHub Handle bopen
? GitHub Repo Path bopen/test
? License MIT
? Package Manager yarn
? Template default
✔ Copying default template to /private/tmp/test
✔ Running yarn install and yarn link
✔ Initializing git repo


Your module has been created at undefined.

To get started, in one tab, run:
$ cd test && yarn start

And in another tab, run the create-react-app devserver:
$ cd test/example && yarn start
```

As you can see it says "Your module has been created at _undefined_." (ok, probably a totally different issue 😄 )

Sorry for bothering!
