### ISSUE TITLE
Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by Xing-He** [transitive-bullshit/create-react-library#72]
I create a `hello world` lib with `npm` and `yarn`,  they both show errors

- os: Mac 10.13.6
- npm: `5.6.0`
- yarn: `1.10.0`
- node: `8.11.3`

## using npm

```bash
localhost:react deme$ create-react-library
? Package Name hello
? Package Description
? Author's GitHub Handle **
? GitHub Repo Path **/hello
? License MIT
? Package Manager npm
? Template default
✔ Copying default template to ~/react/hello
✖ Running npm install and npm link
{ Error: Command failed: /bin/sh -c npm install

src/index.js → dist/index.js, dist/index.es.js...
[!] (postcss plugin) Error: EISDIR: illegal operation on a directory, read
src/styles.css
Error: EISDIR: illegal operation on a directory, read

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello@1.0.0 build: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hello@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-09-28T03_35_05_052Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello@1.0.0 prepare: `npm run build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the hello@1.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     ~/.npm/_logs/2018-09-28T03_35_05_297Z-debug.log
```

#### some log in `2018-09-28T03_35_05_297Z-debug.log`

```
40801 verbose lifecycle hello@1.0.0~prepare: CWD: /Users/deme/Code/me.github/demos/react/hello
40802 silly lifecycle hello@1.0.0~prepare: Args: [ '-c', 'npm run build' ]
40803 silly lifecycle hello@1.0.0~prepare: Returned: code: 1  signal: null
40804 info lifecycle hello@1.0.0~prepare: Failed to exec prepare script
40805 verbose stack Error: hello@1.0.0 prepare: `npm run build`
40805 verbose stack Exit status 1
40805 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
40805 verbose stack     at emitTwo (events.js:126:13)
40805 verbose stack     at EventEmitter.emit (events.js:214:7)
40805 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
40805 verbose stack     at emitTwo (events.js:126:13)
40805 verbose stack     at ChildProcess.emit (events.js:214:7)
40805 verbose stack     at maybeClose (internal/child_process.js:925:16)
40805 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
40806 verbose pkgid hello@1.0.0
40807 verbose cwd /Users/deme/Code/me.github/demos/react/hello
40808 verbose Darwin 17.7.0
40809 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
40810 verbose node v8.11.3
40811 verbose npm  v5.6.0
40812 error code ELIFECYCLE
40813 error errno 1
40814 error hello@1.0.0 prepare: `npm run build`
40814 error Exit status 1
40815 error Failed at the hello@1.0.0 prepare script.
40815 error This is probably not a problem with npm. There is likely additional logging output above.
40816 verbose exit [ 1, true ]
```

## using yarn

```bash
? Package Name hello
? Package Description
? Author's GitHub Handle **
? GitHub Repo Path **/hello
? License MIT
? Package Manager yarn
? Template default
✔ Copying default template to ~/hello
✖ Running yarn install and yarn link
{ Error: Command failed: /bin/sh -c yarn install
error An unexpected error occurred: "EISDIR: illegal operation on a directory, read".

yarn install v1.10.0
info If you think this is a bug, please open a bug report with the information provided in "~/hello/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

    at makeError (/usr/local/lib/node_modules/create-react-library/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/usr/local/lib/node_modules/create-react-library/node_modules/execa/index.js:277:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  stdout: 'yarn install v1.10.0\ninfo If you think this is a bug, please open a bug report with the information provided in "~/hello/yarn-error.log".\ninfo Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.\n',
  stderr: 'error An unexpected error occurred: "EISDIR: illegal operation on a directory, read".\n',
  failed: true,
  signal: null,
  cmd: '/bin/sh -c yarn install',
  timedOut: false,
  killed: false }
```

**Comment by Xing-He** [comment]
Sorry for bothering! I just resolved this error, becase i have a `higher up` directory named `package.json`

**Comment by pm02446** [comment]
Question what do you mean by " i have a higher up directory named package.json"

**Comment by wellermiranda** [comment]
> Question what do you mean by " i have a higher up directory named package.json"

Thank you :)
